apiVersion: v1
kind: Service
metadata:
  labels:
    app: pervertxdocker
  name: pervertxdocker
spec:
  ports:
    -
      name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: pervertxdocker
  type: LoadBalancer
